FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY BACKEND/requerimientos.txt .
RUN pip install --no-cache-dir -r requerimientos.txt

COPY ./BACKEND /app/
COPY ./BACKEND/wait-for-db.py /app/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
